language: objective-c
rvm: 2.0.0
osx_image: xcode8.2
jdk: oraclejdk8
cache:
  directories:
  - node_modules
  - $HOME/.m2
  - $HOME/.gradle
before_install:
  - gem install danger danger-xcode_summary xcpretty xcpretty-json-formatter
  - brew update
  - source test/setup-android-ci.sh && installAndroidSDK
  - createAndStartAVD &
  - brew install nvm
  - export CHROME_BIN=chromium-browser
  - source $(brew --prefix nvm)/nvm.sh
  - nvm install 4.2.1
  - brew install ios-webkit-debug-proxy
  - npm install -g macaca-cli
  #- npm install -g macaca-ios
  - "JAVA_HOME=$(/usr/libexec/java_home) npm install -g macaca-android"
  - npm install
before_script:
  - "export DISPLAY=:99.0"
script:
  #- xcodebuild -project ios/sdk/WeexSDK.xcodeproj test -scheme WeexSDKTests CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPhone 6' | XCPRETTY_JSON_FILE_OUTPUT=ios/sdk/xcodebuild.json xcpretty -f `xcpretty-json-formatter`
  #- bundle exec danger
  - npm run build
  - npm run test
  - ./test/serve.sh 2&>1 > /dev/null &
  # - "run_in_ci=true ./test/run.sh ios"
  - cd android && ./run-ci.sh
  - waitForEmulator #android-wait-for-emulator
  - "JAVA_HOME=$(/usr/libexec/java_home) ./test/run.sh"
  
